name: 'Configuration Exporter'
type: module
description: 'Provides a REST endpoint for exporting site configurations.'
core_version_requirement: ^10
package: Custom
dependencies:
  - drupal:rest
  - drupal:serialization
