config_exporter.admin_settings:
  path: '/admin/config/system/config-manager'
  defaults:
    _form: '\Drupal\config_exporter\Form\ConfigManagerForm'
    _title: 'Configuration Manager'
  requirements:
    _permission: 'administer site configuration'
