<?php

/**
 * Implements hook_install().
 */
function rate_limit_install() {
  // Set default values for configs.
  \Drupal::configFactory()->getEditable('rate_limit.settings')
    ->set('count_limit', 5)
    ->set('time_limit', 30) // In seconds.
    ->save();
}

/**
 * Implements hook_schema().
 */
function rate_limit_schema() {
  $schema['rate_limit'] = [
    'description' => 'Stores access details per IP addresses.',
    'fields' => [
      'ip' => [
        'description' => 'IP address',
        'type' => 'varchar_ascii',
        'length' => 40,
        'not null' => TRUE,
        'default' => '',
      ],
      'timestamp' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'Unix timestamp of when api accessed.',
        'size' => 'big',
      ],
      'count' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The api access counter.',
      ],
    ],
    'primary key' => ['ip'],
  ];
  return $schema;
}
